# Punto 4

In [1]:
import pandas as pd
import matplotlib as mlt
import numpy as np
import matplotlib.pyplot as plt
import cv2
import PyQt5

In [2]:
# Para que las gráficas se impriman no en el notebook, sino en una nueva pestaña
%matplotlib qt

## Punto 4 a

In [3]:
# Lectura de los datos

a = pd.read_csv('a.csv', header=None)              # Lecutra del .csv como un objeto np.array

# Dado que la información del csv se carga como texto y además los complejos tienen i en vez de j
# se convertirán esos textos a números complejos
a = a.applymap(lambda s: complex(s.replace('i', 'j'))).values       # Tomado de https://stackoverflow.com/questions/18280489/numpy-read-csv-with-complex-number

In [4]:
# Función para plotear complejos

def fun_ploteo_complejo(mat, indicador, escala, mapa_color = 'gray'):
    '''
    mat  es una matriz compleja a plotear
    indicador = I para intensidad, A para amplitud, P para fase
    escala = 1 para nada, 0 para logarítmica
    '''
    if(indicador =="I"):
        mat = np.abs(mat)**2
    elif(indicador == "A"):
        mat = np.abs(mat)
    elif(indicador == "P"):
        mat = np.angle(mat)

    if (escala == 1):
        plt.figure()
        plt.imshow(mat, cmap = mapa_color)
        plt.colorbar()
        plt.show()
    else:    
        plt.figure()
        plt.imshow( np.log( mat + 0.001), cmap = mapa_color)
        plt.colorbar()
        plt.show()




In [5]:
fun_ploteo_complejo(a,"A", 0)

# Se puede apreciar que en ese campo no hay una imagen discernible

In [6]:
# Por lo que podemos observar como se 
fun_ploteo_complejo(a,"P", 1)

# Se puede apreciar un patrón en en el centro como dos semiesferas

In [7]:
np.imag(a[0][0])
print(np.angle(a[0][0]), np.sqrt(np.real(a[0][0])**2 + np.imag(a[0][0])**2), np.abs(a[0][0]), np.tan(np.imag(a[0][0])/np.real(a[0][0]) ) )

-0.4619989196455577 0.9999999999999996 0.9999999999999996 -0.5436317736040365


In [8]:
#Creación de la máscara

mask_4a = np.zeros(np.shape(a), dtype = "uint8") # uint8 tipo de la variable de la matriz (enteros de 8 bit)

# Como mi imagen no es cuadrada, entonces necesito dos coordenadas
# para el centro
coord0 = int(np.shape(a)[0]/2)
coord1 = int(np.shape(a)[1]/2)

print(coord0, coord1)

#Graficar la máscara circular 
cv2.circle(mask_4a, (coord1, coord0), 50, 1, -1)
#arg1  #arg2 = posiciones de columnas #arg 3=pixeles dentro de la máscara # arg4 = que me rellene todo
plt.figure()
plt.imshow(mask_4a)
plt.colorbar() # Para mostrar barra de colores
plt.show()

360 360


In [9]:
#Transformada de la matriz a
fft_a = np.fft.fftn(a)

# Shifteada
fft_a_shifted = np.fft.fftshift(fft_a)

# Aplicando la máscara (en el espacio de frecuencias)
fft_a_filtrada = fft_a_shifted*mask_4a

# Regresando al espacio real aplicando la máscara
a_filtrada = np.fft.ifftn(fft_a_filtrada)

# Gráfica de la máscara
fun_ploteo_complejo(mask_4a, "A", 0)

# Gráfica de la transformada shifteada
fun_ploteo_complejo(fft_a_shifted, "A", 0)
#Grágica de la fase de la transformada
fun_ploteo_complejo(fft_a_shifted, "P", 1, 'viridis')


# Gráfica de la transformada * máscara
fun_ploteo_complejo(fft_a_filtrada, "A", 0)

# Gráfica de la imagen real despues de filtrar la transformada con la máscara
fun_ploteo_complejo(a_filtrada, "A", 1)


In [10]:


plt.figure()
plt.hist(np.real(a))
plt.show()


plt.figure()
plt.hist(np.imag(a))
plt.show()


plt.figure()
plt.hist(np.abs(a))
plt.show()

plt.figure()
plt.hist(np.angle(a))
plt.show()

In [11]:
plt.hist(np.abs(a))

(array([[ 16.,   0.,  58., ..., 130., 200.,  82.],
        [ 13.,   3.,  61., ..., 131., 198.,  72.],
        [ 17.,   0.,  40., ..., 139., 180.,  73.],
        ...,
        [  9.,   3.,  56., ..., 146., 181.,  82.],
        [ 10.,   3.,  54., ..., 140., 191.,  71.],
        [  6.,   8.,  46., ..., 141., 193.,  75.]]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 <a list of 720 BarContainer objects>)

In [12]:
plt.hist(np.angle(a))

(array([[  5.,  27., 172., ...,   0.,   0.,  13.],
        [  6.,  21., 185., ...,   1.,   1.,  11.],
        [ 11.,  24., 191., ...,   0.,   0.,  11.],
        ...,
        [ 16.,  14.,  90., ...,   1.,   0.,   0.],
        [ 17.,  15.,  86., ...,   3.,   0.,   0.],
        [ 16.,  18.,  96., ...,   3.,   0.,   0.]]),
 array([-1.57079633, -1.25663706, -0.9424778 , -0.62831853, -0.31415927,
         0.        ,  0.31415927,  0.62831853,  0.9424778 ,  1.25663706,
         1.57079633]),
 <a list of 720 BarContainer objects>)

# Punto 4 c

In [5]:
# Lectura de los datos

war_img = cv2.imread('c.jpeg')              # Lecutra del .csv como un objeto np.array
waly_img = cv2.imread('c_clue.jpeg')
# Dado que la información del csv se carga como texto y además los complejos tienen i en vez de j
# se convertirán esos textos a números complejos


In [6]:
# Veamos las dimensiones de las imágenes
print("dimensiones de la imagen de guerra: " ,np.shape(war_img), "\ndimensiones de waly: ", np.shape(waly_img) )

# Cambiar a RGB
war_img = cv2.cvtColor(war_img, cv2.COLOR_BGR2RGB)
waly_img = cv2.cvtColor(waly_img, cv2.COLOR_BGR2RGB)

# Mostrar imágenes
plt.figure()
plt.imshow(war_img)
plt.show()

plt.figure()
plt.imshow(waly_img)
plt.show()

dimensiones de la imagen de guerra:  (1680, 2600, 3) 
dimensiones de waly:  (64, 64, 3)


Como tenemos imágnes RGB, entonces por facilidad las pasaremos a escala de grices, después si se desea, 
generalizamos para imágenes RGB

In [7]:
# Convertir imágenes RGB a escala de grises
war_gray = cv2.cvtColor(war_img, cv2.COLOR_RGB2GRAY)
waly_gray = cv2.cvtColor(waly_img, cv2.COLOR_RGB2GRAY)

# Mostrar imágenes
plt.figure()
plt.imshow(war_gray, cmap = 'gray')
plt.show()

plt.figure()
plt.imshow(waly_gray, cmap = 'gray')
plt.show()

In [19]:
# Transformadas de Fourier a las imágenes
fft_war = np.fft.fftn(war_gray)
fft_waly = np.fft.fftn(waly_gray)

# Shifteando
ffts_war = np.fft.fftshift(fft_war)
ffts_waly = np.fft.fftshift(fft_waly)

# Graficando las transofrmadas
fun_ploteo_complejo(ffts_war, "I", 0)
fun_ploteo_complejo(ffts_waly, "I", 0)

In [25]:
# convolucion = cv2.filter2D(gray_imagen_guerra, ddepth = -1, kernel = gray_waly)
# plt.figure()
# plt.imshow(convolucion, cmap = 'gray')
# plt.show()

# Pad

In [21]:
dimension_pad = (np.array(np.shape(war_gray) ) - np.array(np.shape(waly_gray) ) )/2
waly_paded = np.pad(waly_gray, ( (int(dimension_pad[0]), int(dimension_pad[0]) ), (int(dimension_pad[1]), int(dimension_pad[1])) ), mode = 'constant', constant_values = (0,0) )

print(np.shape(waly_paded) )
#plt.imshow(waly_paded)
# Fourier
fft_p_waly = np.fft.fftn(waly_paded)
ffts_p_waly = np.fft.fftshift(fft_p_waly)       #Shift

filtrada = ffts_war * ffts_p_waly


#Graficando
fun_ploteo_complejo(ffts_p_waly, "I", 0)
fun_ploteo_complejo(ffts_war, "I" , 0)
fun_ploteo_complejo(filtrada, "I", 0)

# Inversa
fun_ploteo_complejo(np.fft.ifftn(filtrada), "I", 1)

(1680, 2600)


# Pad de la transformada


In [18]:
p_ffts_waly = np.pad(ffts_waly, ( (int(dimension_pad[0]), int(dimension_pad[0]) ), (int(dimension_pad[1]), int(dimension_pad[1])) ), mode = 'constant', constant_values = (0,0) )

filtrada2 = ffts_war * p_ffts_waly

# Graficando
fun_ploteo_complejo(p_ffts_waly, "I", 0)
fun_ploteo_complejo(ffts_war, "I" , 0)
fun_ploteo_complejo(filtrada2, "I", 0)

# Inversa
fun_ploteo_complejo(np.fft.ifftn(filtrada2), "I", 0)